apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260520-135112-n2bry4u9v4qq-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260520-135112-n2bry4u9v4qq.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260520-135112-n2bry4u9v4qq-service
            port:
              number: 80
