apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260520-135112-n2bry4u9v4qq-service
spec:
  selector:
    app: enterprise-system-20260520-135112-n2bry4u9v4qq
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
